export enum QueryType {
    SEARCH_PRODUCT = 'SEARCH_PRODUCT',
    PRODUCT_INFO = 'PRODUCT_INFO',
    PLATFORM_INFO = 'PLATFORM_INFO',
    PLATFORM_HELP = 'PLATFORM_HELP',
    TRANSACTION_HELP = 'TRANSACTION_HELP',
    ACCOUNT_MGMT = 'ACCOUNT_MGMT',
    SELLER_SUPPORT = 'SELLER_SUPPORT',
    OTHER = 'OTHER'
  }